//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pactera.TOIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.10.0.251:8080/services/TOIService", ConfigurationName="TOIService.TOIService")]
    public interface TOIService {
        
        // CODEGEN: 消息 mainRequest 的包装命名空间(http://WS.cnqc.software.com)以后生成的消息协定与默认值(http://10.10.0.251:8080/services/TOIService)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        global::Pactera.TOIService.mainResponse main(global::Pactera.TOIService.mainRequest request);
        
        // CODEGEN: 消息 addTOIRequest 的包装命名空间(http://WS.cnqc.software.com)以后生成的消息协定与默认值(http://10.10.0.251:8080/services/TOIService)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        global::Pactera.TOIService.addTOIResponse addTOI(global::Pactera.TOIService.addTOIRequest request);
        
        // CODEGEN: 消息 getKeyCodeRequest 的包装命名空间(http://WS.cnqc.software.com)以后生成的消息协定与默认值(http://10.10.0.251:8080/services/TOIService)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        global::Pactera.TOIService.getKeyCodeResponse getKeyCode(global::Pactera.TOIService.getKeyCodeRequest request);
        
        // CODEGEN: 消息 editTOIRequest 的包装命名空间(http://WS.cnqc.software.com)以后生成的消息协定与默认值(http://10.10.0.251:8080/services/TOIService)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        global::Pactera.TOIService.editTOIResponse editTOI(global::Pactera.TOIService.editTOIRequest request);
        
        // CODEGEN: 消息 delTOIRequest 的包装命名空间(http://WS.cnqc.software.com)以后生成的消息协定与默认值(http://10.10.0.251:8080/services/TOIService)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        global::Pactera.TOIService.delTOIResponse delTOI(global::Pactera.TOIService.delTOIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="main", WrapperNamespace="http://WS.cnqc.software.com", IsWrapped=true)]
    public partial class mainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] args;
        
        public mainRequest() {
        }
        
        public mainRequest(string[] args) {
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mainResponse", WrapperNamespace="http://10.10.0.251:8080/services/TOIService", IsWrapped=true)]
    public partial class mainResponse {
        
        public mainResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addTOI", WrapperNamespace="http://WS.cnqc.software.com", IsWrapped=true)]
    public partial class addTOIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string jsonString;
        
        public addTOIRequest() {
        }
        
        public addTOIRequest(string jsonString) {
            this.jsonString = jsonString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addTOIResponse", WrapperNamespace="http://10.10.0.251:8080/services/TOIService", IsWrapped=true)]
    public partial class addTOIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string addTOIReturn;
        
        public addTOIResponse() {
        }
        
        public addTOIResponse(string addTOIReturn) {
            this.addTOIReturn = addTOIReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeyCode", WrapperNamespace="http://WS.cnqc.software.com", IsWrapped=true)]
    public partial class getKeyCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string EnuType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string EnuItemLabel;
        
        public getKeyCodeRequest() {
        }
        
        public getKeyCodeRequest(string EnuType, string EnuItemLabel) {
            this.EnuType = EnuType;
            this.EnuItemLabel = EnuItemLabel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeyCodeResponse", WrapperNamespace="http://10.10.0.251:8080/services/TOIService", IsWrapped=true)]
    public partial class getKeyCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getKeyCodeReturn;
        
        public getKeyCodeResponse() {
        }
        
        public getKeyCodeResponse(string getKeyCodeReturn) {
            this.getKeyCodeReturn = getKeyCodeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editTOI", WrapperNamespace="http://WS.cnqc.software.com", IsWrapped=true)]
    public partial class editTOIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string jsonString;
        
        public editTOIRequest() {
        }
        
        public editTOIRequest(string jsonString) {
            this.jsonString = jsonString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editTOIResponse", WrapperNamespace="http://10.10.0.251:8080/services/TOIService", IsWrapped=true)]
    public partial class editTOIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string editTOIReturn;
        
        public editTOIResponse() {
        }
        
        public editTOIResponse(string editTOIReturn) {
            this.editTOIReturn = editTOIReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delTOI", WrapperNamespace="http://WS.cnqc.software.com", IsWrapped=true)]
    public partial class delTOIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string jsonString;
        
        public delTOIRequest() {
        }
        
        public delTOIRequest(string jsonString) {
            this.jsonString = jsonString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delTOIResponse", WrapperNamespace="http://10.10.0.251:8080/services/TOIService", IsWrapped=true)]
    public partial class delTOIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string delTOIReturn;
        
        public delTOIResponse() {
        }
        
        public delTOIResponse(string delTOIReturn) {
            this.delTOIReturn = delTOIReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TOIServiceChannel : global::Pactera.TOIService.TOIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TOIServiceClient : System.ServiceModel.ClientBase<global::Pactera.TOIService.TOIService>, global::Pactera.TOIService.TOIService {
        
        public TOIServiceClient() {
        }
        
        public TOIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TOIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TOIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TOIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Pactera.TOIService.mainResponse global::Pactera.TOIService.TOIService.main(global::Pactera.TOIService.mainRequest request) {
            return base.Channel.main(request);
        }
        
        public void main(string[] args) {
            global::Pactera.TOIService.mainRequest inValue = new global::Pactera.TOIService.mainRequest();
            inValue.args = args;
            global::Pactera.TOIService.mainResponse retVal = ((global::Pactera.TOIService.TOIService)(this)).main(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Pactera.TOIService.addTOIResponse global::Pactera.TOIService.TOIService.addTOI(global::Pactera.TOIService.addTOIRequest request) {
            return base.Channel.addTOI(request);
        }
        
        public string addTOI(string jsonString) {
            global::Pactera.TOIService.addTOIRequest inValue = new global::Pactera.TOIService.addTOIRequest();
            inValue.jsonString = jsonString;
            global::Pactera.TOIService.addTOIResponse retVal = ((global::Pactera.TOIService.TOIService)(this)).addTOI(inValue);
            return retVal.addTOIReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Pactera.TOIService.getKeyCodeResponse global::Pactera.TOIService.TOIService.getKeyCode(global::Pactera.TOIService.getKeyCodeRequest request) {
            return base.Channel.getKeyCode(request);
        }
        
        public string getKeyCode(string EnuType, string EnuItemLabel) {
            global::Pactera.TOIService.getKeyCodeRequest inValue = new global::Pactera.TOIService.getKeyCodeRequest();
            inValue.EnuType = EnuType;
            inValue.EnuItemLabel = EnuItemLabel;
            global::Pactera.TOIService.getKeyCodeResponse retVal = ((global::Pactera.TOIService.TOIService)(this)).getKeyCode(inValue);
            return retVal.getKeyCodeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Pactera.TOIService.editTOIResponse global::Pactera.TOIService.TOIService.editTOI(global::Pactera.TOIService.editTOIRequest request) {
            return base.Channel.editTOI(request);
        }
        
        public string editTOI(string jsonString) {
            global::Pactera.TOIService.editTOIRequest inValue = new global::Pactera.TOIService.editTOIRequest();
            inValue.jsonString = jsonString;
            global::Pactera.TOIService.editTOIResponse retVal = ((global::Pactera.TOIService.TOIService)(this)).editTOI(inValue);
            return retVal.editTOIReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Pactera.TOIService.delTOIResponse global::Pactera.TOIService.TOIService.delTOI(global::Pactera.TOIService.delTOIRequest request) {
            return base.Channel.delTOI(request);
        }
        
        public string delTOI(string jsonString) {
            global::Pactera.TOIService.delTOIRequest inValue = new global::Pactera.TOIService.delTOIRequest();
            inValue.jsonString = jsonString;
            global::Pactera.TOIService.delTOIResponse retVal = ((global::Pactera.TOIService.TOIService)(this)).delTOI(inValue);
            return retVal.delTOIReturn;
        }
    }
}
