//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pactera.BIDService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.10.0.251:8080/services/BidProService", ConfigurationName="BIDService.BidProService")]
    public interface BidProService {
        
        // CODEGEN: 消息 mainRequest 的包装命名空间(http://WS.cnqc.software.com)以后生成的消息协定与默认值(http://10.10.0.251:8080/services/BidProService)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        global::Pactera.BIDService.mainResponse main(global::Pactera.BIDService.mainRequest request);
        
        // CODEGEN: 消息 addBidProRequest 的包装命名空间(http://WS.cnqc.software.com)以后生成的消息协定与默认值(http://10.10.0.251:8080/services/BidProService)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        global::Pactera.BIDService.addBidProResponse addBidPro(global::Pactera.BIDService.addBidProRequest request);
        
        // CODEGEN: 消息 editBidProRequest 的包装命名空间(http://WS.cnqc.software.com)以后生成的消息协定与默认值(http://10.10.0.251:8080/services/BidProService)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        global::Pactera.BIDService.editBidProResponse editBidPro(global::Pactera.BIDService.editBidProRequest request);
        
        // CODEGEN: 消息 delBidProRequest 的包装命名空间(http://WS.cnqc.software.com)以后生成的消息协定与默认值(http://10.10.0.251:8080/services/BidProService)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        global::Pactera.BIDService.delBidProResponse delBidPro(global::Pactera.BIDService.delBidProRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="main", WrapperNamespace="http://WS.cnqc.software.com", IsWrapped=true)]
    public partial class mainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] args;
        
        public mainRequest() {
        }
        
        public mainRequest(string[] args) {
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mainResponse", WrapperNamespace="http://10.10.0.251:8080/services/BidProService", IsWrapped=true)]
    public partial class mainResponse {
        
        public mainResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addBidPro", WrapperNamespace="http://WS.cnqc.software.com", IsWrapped=true)]
    public partial class addBidProRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string jsonString;
        
        public addBidProRequest() {
        }
        
        public addBidProRequest(string jsonString) {
            this.jsonString = jsonString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addBidProResponse", WrapperNamespace="http://10.10.0.251:8080/services/BidProService", IsWrapped=true)]
    public partial class addBidProResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string addBidProReturn;
        
        public addBidProResponse() {
        }
        
        public addBidProResponse(string addBidProReturn) {
            this.addBidProReturn = addBidProReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editBidPro", WrapperNamespace="http://WS.cnqc.software.com", IsWrapped=true)]
    public partial class editBidProRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string jsonString;
        
        public editBidProRequest() {
        }
        
        public editBidProRequest(string jsonString) {
            this.jsonString = jsonString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editBidProResponse", WrapperNamespace="http://10.10.0.251:8080/services/BidProService", IsWrapped=true)]
    public partial class editBidProResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string editBidProReturn;
        
        public editBidProResponse() {
        }
        
        public editBidProResponse(string editBidProReturn) {
            this.editBidProReturn = editBidProReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delBidPro", WrapperNamespace="http://WS.cnqc.software.com", IsWrapped=true)]
    public partial class delBidProRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string pk_project;
        
        public delBidProRequest() {
        }
        
        public delBidProRequest(string pk_project) {
            this.pk_project = pk_project;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delBidProResponse", WrapperNamespace="http://10.10.0.251:8080/services/BidProService", IsWrapped=true)]
    public partial class delBidProResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string delBidProReturn;
        
        public delBidProResponse() {
        }
        
        public delBidProResponse(string delBidProReturn) {
            this.delBidProReturn = delBidProReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BidProServiceChannel : global::Pactera.BIDService.BidProService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BidProServiceClient : System.ServiceModel.ClientBase<global::Pactera.BIDService.BidProService>, global::Pactera.BIDService.BidProService {
        
        public BidProServiceClient() {
        }
        
        public BidProServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BidProServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BidProServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BidProServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Pactera.BIDService.mainResponse global::Pactera.BIDService.BidProService.main(global::Pactera.BIDService.mainRequest request) {
            return base.Channel.main(request);
        }
        
        public void main(string[] args) {
            global::Pactera.BIDService.mainRequest inValue = new global::Pactera.BIDService.mainRequest();
            inValue.args = args;
            global::Pactera.BIDService.mainResponse retVal = ((global::Pactera.BIDService.BidProService)(this)).main(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Pactera.BIDService.addBidProResponse global::Pactera.BIDService.BidProService.addBidPro(global::Pactera.BIDService.addBidProRequest request) {
            return base.Channel.addBidPro(request);
        }
        
        public string addBidPro(string jsonString) {
            global::Pactera.BIDService.addBidProRequest inValue = new global::Pactera.BIDService.addBidProRequest();
            inValue.jsonString = jsonString;
            global::Pactera.BIDService.addBidProResponse retVal = ((global::Pactera.BIDService.BidProService)(this)).addBidPro(inValue);
            return retVal.addBidProReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Pactera.BIDService.editBidProResponse global::Pactera.BIDService.BidProService.editBidPro(global::Pactera.BIDService.editBidProRequest request) {
            return base.Channel.editBidPro(request);
        }
        
        public string editBidPro(string jsonString) {
            global::Pactera.BIDService.editBidProRequest inValue = new global::Pactera.BIDService.editBidProRequest();
            inValue.jsonString = jsonString;
            global::Pactera.BIDService.editBidProResponse retVal = ((global::Pactera.BIDService.BidProService)(this)).editBidPro(inValue);
            return retVal.editBidProReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Pactera.BIDService.delBidProResponse global::Pactera.BIDService.BidProService.delBidPro(global::Pactera.BIDService.delBidProRequest request) {
            return base.Channel.delBidPro(request);
        }
        
        public string delBidPro(string pk_project) {
            global::Pactera.BIDService.delBidProRequest inValue = new global::Pactera.BIDService.delBidProRequest();
            inValue.pk_project = pk_project;
            global::Pactera.BIDService.delBidProResponse retVal = ((global::Pactera.BIDService.BidProService)(this)).delBidPro(inValue);
            return retVal.delBidProReturn;
        }
    }
}
